### ISSUE TITLE
Unique index lost when renaming a ManyToManyField

### ISSUE THREAD

**Issue by sparrowt** [microsoft/mssql-django#86]
### Problem
When doing `migrations.RenameField` on a field which is a `models.ManyToManyField`, the filtered `UNIQUE INDEX` (which enforces the uniqueness constraint on A_ID,B_ID pairs on the through table) is dropped before the rename, but not re-instated afterwards ⚠

### Example
So I see something like this:
```
DROP INDEX myapp_mymodel_fieldname_x_id_y_id_uniq ON myapp_mymodel_fieldname
EXEC sp_rename [myapp_mymodel_fieldname], [myapp_mymodel_newfieldname]
```
and aftewards the dropped index is missing.

The lost index is the one created earlier (when the m2m field was added) to enforce the `unique_together` constraint on the 2 ID fields (on the through model which `create_many_to_many_intermediary_model` generates) something like this:
```
CREATE UNIQUE INDEX [myapp_mymodel_fieldname_x_id_y_id_uniq ] ON [myapp_mymodel_fieldname] ([x_id], [y_id]) WHERE [x_id] IS NOT NULL AND [y_id] IS NOT NULL
```

### Cause
This seems to be the code at fault: https://github.com/microsoft/mssql-django/blame/1.1.1/mssql/schema.py#L231-L232 which came in https://github.com/ESSolutions/django-mssql-backend/pull/24 where `unique_together` was first changed to be implemented by a filtered-unique-index rather than a constraint (in order to support nullability).

### Test
I've written a regression test which fails due to the above bug: https://github.com/microsoft/mssql-django/pull/88

**Comment by absci** [comment]
Thanks for the added unit test.

**Comment by sparrowt** [comment]
I have pushed the proposed fix to the same PR: https://github.com/microsoft/mssql-django/pull/88, let me know what you think

**Comment by absci** [comment]
Close as the fix has been merged.

**Comment by sparrowt** [comment]
Thanks @absci - is there any chance of a new release soon please?

I'm hoping to officially start using this project as soon as it is published, and don't really want to start building my own wheels.

**Comment by sparrowt** [comment]
Unfortunately this is blocking us as follows:
 - we cannot upgrade to this fork `microsoft/mssql-django` (from `ESSolutions/django-mssql-backend`) until a new version is released with the fixes which are already in `dev`
 - we cannot upgrade to Django 3 until we have done the above upgrade (because to get Django 3 support, we would need to upgrade and get at a minimum [all of these changes](https://github.com/ESSolutions/django-mssql-backend/compare/2.4.2...2.6.0) which introduced a bunch of bugs, all of which are now finally resolved in latest `microsoft/mssql-django:dev`)
 - Django 2.2 LTS goes out of support in _April_ 2022 i.e. next month (https://www.djangoproject.com/download/#supported-versions)

So it would be very much appreciated to have a release within the next month - otherwise we will be stuck on out-of-support Django, or have to consider trying to build our own "1.1.3" wheel off `dev` until an official one comes out.

Given the fixes are already merged, hopefully only a version bump is required? I'm happy to open that PR. Many thanks.

**Comment by vwarchu** [comment]
@sparrowt - Thanks for the context. Our team is now aiming to release by end of April, sooner if possible. We'll keep you posted.

**Comment by sparrowt** [comment]
Many thanks @vwarchu!

**Comment by vwarchu** [comment]
@sparrowt - We've now released version 1.1.3 which includes the aforementioned merges. Cheers

**Comment by sparrowt** [comment]
That's brilliant, thank you!

**Comment by sparrowt** [comment]
P.S. is it expected that https://github.com/microsoft/mssql-django/compare/1.1.3...dev (and https://github.com/microsoft/mssql-django/compare/master...dev) still shows all those commits as missing from master/1.1.3 (and https://github.com/microsoft/mssql-django/compare/1.1.2...1.1.3 only has 1 commit)?

Perhaps because https://github.com/microsoft/mssql-django/pull/124 was squash-merged?

It would seem preferable if git blame on master showed the original commit messages, rather than "prepare for 1.1.3 release" like it now does e.g. here https://github.com/microsoft/mssql-django/blame/master/mssql/schema.py#L233
